// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using OvcinaHra.Api.Data;

#nullable disable

namespace OvcinaHra.Api.Migrations
{
    [DbContext(typeof(WorldDbContext))]
    [Migration("20260414120039_AddNpcBirthDeathYear")]
    partial class AddNpcBirthDeathYear
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.BattlefieldBonus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttackBonus")
                        .HasColumnType("integer");

                    b.Property<int>("DefenseBonus")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("BattlefieldBonuses");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<bool>("IsPrebuilt")
                        .HasColumnType("boolean");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExternalPersonId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPlayedCharacter")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("ParentCharacterId")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PlayerLastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Race")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalPersonId")
                        .IsUnique()
                        .HasFilter("\"ExternalPersonId\" IS NOT NULL");

                    b.HasIndex("ParentCharacterId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.CharacterAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<string>("Class")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExternalPersonId")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Kingdom")
                        .HasColumnType("text");

                    b.Property<int?>("RegistraceCharacterId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ExternalPersonId");

                    b.HasIndex("GameId");

                    b.HasIndex("GameId", "ExternalPersonId")
                        .IsUnique();

                    b.ToTable("CharacterAssignments");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.CharacterEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterAssignmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("OrganizerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganizerUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CharacterAssignmentId");

                    b.ToTable("CharacterEvents");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.CraftingBuildingRequirement", b =>
                {
                    b.Property<int>("CraftingRecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer");

                    b.HasKey("CraftingRecipeId", "BuildingId");

                    b.HasIndex("BuildingId");

                    b.ToTable("CraftingBuildingRequirements");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.CraftingIngredient", b =>
                {
                    b.Property<int>("CraftingRecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("CraftingRecipeId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("CraftingIngredients");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.CraftingRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer");

                    b.Property<int>("OutputItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("LocationId");

                    b.HasIndex("OutputItemId");

                    b.ToTable("CraftingRecipes");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Edition")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int?>("ExternalGameId")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.GameBuilding", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer");

                    b.HasKey("GameId", "BuildingId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("GameId");

                    b.ToTable("GameBuildings");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.GameEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameEvents");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.GameEventLocation", b =>
                {
                    b.Property<int>("GameEventId")
                        .HasColumnType("integer");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.HasKey("GameEventId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("GameEventLocations");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.GameEventNpc", b =>
                {
                    b.Property<int>("GameEventId")
                        .HasColumnType("integer");

                    b.Property<int>("NpcId")
                        .HasColumnType("integer");

                    b.Property<string>("RoleInEvent")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("GameEventId", "NpcId");

                    b.HasIndex("NpcId");

                    b.ToTable("GameEventNpcs");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.GameEventQuest", b =>
                {
                    b.Property<int>("GameEventId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestId")
                        .HasColumnType("integer");

                    b.HasKey("GameEventId", "QuestId");

                    b.HasIndex("QuestId");

                    b.ToTable("GameEventQuests");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.GameEventTimeSlot", b =>
                {
                    b.Property<int>("GameEventId")
                        .HasColumnType("integer");

                    b.Property<int>("GameTimeSlotId")
                        .HasColumnType("integer");

                    b.HasKey("GameEventId", "GameTimeSlotId");

                    b.HasIndex("GameTimeSlotId");

                    b.ToTable("GameEventTimeSlots");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.GameItem", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFindable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSold")
                        .HasColumnType("boolean");

                    b.Property<int?>("Price")
                        .HasColumnType("integer");

                    b.Property<string>("SaleCondition")
                        .HasColumnType("text");

                    b.Property<int?>("StockCount")
                        .HasColumnType("integer");

                    b.HasKey("GameId", "ItemId");

                    b.HasIndex("GameId");

                    b.HasIndex("ItemId");

                    b.ToTable("GameItems");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.GameLocation", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.HasKey("GameId", "LocationId");

                    b.HasIndex("GameId");

                    b.HasIndex("LocationId");

                    b.ToTable("GameLocations");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.GameMonster", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("MonsterId")
                        .HasColumnType("integer");

                    b.HasKey("GameId", "MonsterId");

                    b.HasIndex("GameId");

                    b.HasIndex("MonsterId");

                    b.ToTable("GameMonsters");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.GameNpc", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("NpcId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PlayedByEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PlayedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("PlayedByPersonId")
                        .HasColumnType("integer");

                    b.HasKey("GameId", "NpcId");

                    b.HasIndex("GameId");

                    b.HasIndex("NpcId");

                    b.HasIndex("PlayedByEmail");

                    b.HasIndex("PlayedByPersonId");

                    b.ToTable("GameNpcs");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.GameSecretStash", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("SecretStashId")
                        .HasColumnType("integer");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.HasKey("GameId", "SecretStashId");

                    b.HasIndex("GameId");

                    b.HasIndex("LocationId");

                    b.HasIndex("SecretStashId");

                    b.ToTable("GameSecretStashes");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.GameTimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BattlefieldBonusId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int?>("InGameYear")
                        .HasColumnType("integer");

                    b.Property<string>("Rules")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BattlefieldBonusId");

                    b.HasIndex("GameId");

                    b.ToTable("GameTimeSlots");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Effect")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<bool>("IsCraftable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLimited")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUnique")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhysicalForm")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasComputedColumnSql("to_tsvector('simple', coalesce(\"Name\", '') || ' ' || coalesce(\"Effect\", ''))", true);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.LocalUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarColor")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Preferences")
                        .HasColumnType("text");

                    b.Property<string>("RegistraceUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("RegistraceUserId")
                        .IsUnique();

                    b.ToTable("LocalUsers");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("GamePotential")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("LocationKind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NpcInfo")
                        .HasColumnType("text");

                    b.Property<int?>("ParentLocationId")
                        .HasColumnType("integer");

                    b.Property<string>("PlacementPhotoPath")
                        .HasColumnType("text");

                    b.Property<string>("Prompt")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasComputedColumnSql("to_tsvector('simple', coalesce(\"Name\", '') || ' ' || coalesce(\"Description\", '') || ' ' || coalesce(\"NpcInfo\", '') || ' ' || coalesce(\"SetupNotes\", '') || ' ' || coalesce(\"Details\", '') || ' ' || coalesce(\"Region\", ''))", true);

                    b.Property<string>("SetupNotes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentLocationId");

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abilities")
                        .HasColumnType("text");

                    b.Property<string>("AiBehavior")
                        .HasColumnType("text");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("MonsterType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("RewardMoney")
                        .HasColumnType("integer");

                    b.Property<string>("RewardNotes")
                        .HasColumnType("text");

                    b.Property<int?>("RewardXp")
                        .HasColumnType("integer");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasComputedColumnSql("to_tsvector('simple', coalesce(\"Name\", '') || ' ' || coalesce(\"Abilities\", '') || ' ' || coalesce(\"AiBehavior\", ''))", true);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("Monsters");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.MonsterLoot", b =>
                {
                    b.Property<int>("MonsterId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("MonsterId", "ItemId", "GameId");

                    b.HasIndex("GameId");

                    b.HasIndex("ItemId");

                    b.ToTable("MonsterLoots");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.MonsterTagLink", b =>
                {
                    b.Property<int>("MonsterId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("MonsterId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("MonsterTagLinks");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.Npc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeathYear")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Npcs");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.Quest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChainOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FullText")
                        .HasColumnType("text");

                    b.Property<int?>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("ParentQuestId")
                        .HasColumnType("integer");

                    b.Property<string>("QuestType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("RewardMoney")
                        .HasColumnType("integer");

                    b.Property<string>("RewardNotes")
                        .HasColumnType("text");

                    b.Property<int?>("RewardXp")
                        .HasColumnType("integer");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasComputedColumnSql("to_tsvector('simple', coalesce(\"Name\", '') || ' ' || coalesce(\"Description\", '') || ' ' || coalesce(\"FullText\", ''))", true);

                    b.Property<string>("TimeSlot")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("ParentQuestId");

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.QuestEncounter", b =>
                {
                    b.Property<int>("QuestId")
                        .HasColumnType("integer");

                    b.Property<int>("MonsterId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("QuestId", "MonsterId");

                    b.HasIndex("MonsterId");

                    b.ToTable("QuestEncounters");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.QuestLocationLink", b =>
                {
                    b.Property<int>("QuestId")
                        .HasColumnType("integer");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.HasKey("QuestId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("QuestLocationLinks");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.QuestReward", b =>
                {
                    b.Property<int>("QuestId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("QuestId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("QuestRewards");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.QuestTagLink", b =>
                {
                    b.Property<int>("QuestId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("QuestId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("QuestTagLinks");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.SecretStash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SecretStashes");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.TreasureItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("TreasureQuestId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("TreasureQuestId");

                    b.HasIndex("GameId", "TreasureQuestId");

                    b.ToTable("TreasureItems");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.TreasureQuest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Clue")
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer");

                    b.Property<int?>("SecretStashId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("LocationId");

                    b.HasIndex("SecretStashId");

                    b.ToTable("TreasureQuests", t =>
                        {
                            t.HasCheckConstraint("CK_TreasureQuest_LocationOrStash", "(\"LocationId\" IS NOT NULL) <> (\"SecretStashId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.BattlefieldBonus", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Game", "Game")
                        .WithMany("BattlefieldBonuses")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.Building", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Location", "Location")
                        .WithMany("Buildings")
                        .HasForeignKey("LocationId");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.Character", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Character", "ParentCharacter")
                        .WithMany("Children")
                        .HasForeignKey("ParentCharacterId");

                    b.Navigation("ParentCharacter");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.CharacterAssignment", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Character", "Character")
                        .WithMany("Assignments")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.CharacterEvent", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.CharacterAssignment", "Assignment")
                        .WithMany("Events")
                        .HasForeignKey("CharacterAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.CraftingBuildingRequirement", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Building", "Building")
                        .WithMany("CraftingRequirements")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvcinaHra.Shared.Domain.Entities.CraftingRecipe", "CraftingRecipe")
                        .WithMany("BuildingRequirements")
                        .HasForeignKey("CraftingRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("CraftingRecipe");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.CraftingIngredient", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.CraftingRecipe", "CraftingRecipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("CraftingRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Item", "Item")
                        .WithMany("CraftingIngredients")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CraftingRecipe");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.CraftingRecipe", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Game", "Game")
                        .WithMany("CraftingRecipes")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Item", "OutputItem")
                        .WithMany()
                        .HasForeignKey("OutputItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Location");

                    b.Navigation("OutputItem");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.GameBuilding", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Building", "Building")
                        .WithMany("GameBuildings")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Game", "Game")
                        .WithMany("GameBuildings")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.GameEvent", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Game", "Game")
                        .WithMany("GameEvents")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.GameEventLocation", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.GameEvent", "GameEvent")
                        .WithMany("EventLocations")
                        .HasForeignKey("GameEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Location", "Location")
                        .WithMany("EventLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameEvent");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.GameEventNpc", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.GameEvent", "GameEvent")
                        .WithMany("EventNpcs")
                        .HasForeignKey("GameEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Npc", "Npc")
                        .WithMany("EventNpcs")
                        .HasForeignKey("NpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameEvent");

                    b.Navigation("Npc");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.GameEventQuest", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.GameEvent", "GameEvent")
                        .WithMany("EventQuests")
                        .HasForeignKey("GameEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Quest", "Quest")
                        .WithMany("EventQuests")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameEvent");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.GameEventTimeSlot", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.GameEvent", "GameEvent")
                        .WithMany("EventTimeSlots")
                        .HasForeignKey("GameEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvcinaHra.Shared.Domain.Entities.GameTimeSlot", "TimeSlot")
                        .WithMany("EventTimeSlots")
                        .HasForeignKey("GameTimeSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameEvent");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.GameItem", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Game", "Game")
                        .WithMany("GameItems")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Item", "Item")
                        .WithMany("GameItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.GameLocation", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Game", "Game")
                        .WithMany("GameLocations")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Location", "Location")
                        .WithMany("GameLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.GameMonster", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Game", "Game")
                        .WithMany("GameMonsters")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Monster", "Monster")
                        .WithMany("GameMonsters")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.GameNpc", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Game", "Game")
                        .WithMany("GameNpcs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Npc", "Npc")
                        .WithMany("GameNpcs")
                        .HasForeignKey("NpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Npc");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.GameSecretStash", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Game", "Game")
                        .WithMany("GameSecretStashes")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Location", "Location")
                        .WithMany("GameSecretStashes")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvcinaHra.Shared.Domain.Entities.SecretStash", "SecretStash")
                        .WithMany("GameSecretStashes")
                        .HasForeignKey("SecretStashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Location");

                    b.Navigation("SecretStash");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.GameTimeSlot", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.BattlefieldBonus", "BattlefieldBonus")
                        .WithMany("TimeSlots")
                        .HasForeignKey("BattlefieldBonusId");

                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Game", "Game")
                        .WithMany("TimeSlots")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BattlefieldBonus");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.Item", b =>
                {
                    b.OwnsOne("OvcinaHra.Shared.Domain.ValueObjects.ClassRequirements", "ClassRequirements", b1 =>
                        {
                            b1.Property<int>("ItemId")
                                .HasColumnType("integer");

                            b1.Property<int>("Archer")
                                .HasColumnType("integer")
                                .HasColumnName("req_archer");

                            b1.Property<int>("Mage")
                                .HasColumnType("integer")
                                .HasColumnName("req_mage");

                            b1.Property<int>("Thief")
                                .HasColumnType("integer")
                                .HasColumnName("req_thief");

                            b1.Property<int>("Warrior")
                                .HasColumnType("integer")
                                .HasColumnName("req_warrior");

                            b1.HasKey("ItemId");

                            b1.ToTable("Items");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.Navigation("ClassRequirements")
                        .IsRequired();
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.Location", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Location", "ParentLocation")
                        .WithMany("Variants")
                        .HasForeignKey("ParentLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("OvcinaHra.Shared.Domain.ValueObjects.GpsCoordinates", "Coordinates", b1 =>
                        {
                            b1.Property<int>("LocationId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Latitude")
                                .HasPrecision(10, 7)
                                .HasColumnType("numeric(10,7)")
                                .HasColumnName("latitude");

                            b1.Property<decimal>("Longitude")
                                .HasPrecision(10, 7)
                                .HasColumnType("numeric(10,7)")
                                .HasColumnName("longitude");

                            b1.HasKey("LocationId");

                            b1.ToTable("Locations");

                            b1.WithOwner()
                                .HasForeignKey("LocationId");
                        });

                    b.Navigation("Coordinates");

                    b.Navigation("ParentLocation");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.Monster", b =>
                {
                    b.OwnsOne("OvcinaHra.Shared.Domain.ValueObjects.CombatStats", "Stats", b1 =>
                        {
                            b1.Property<int>("MonsterId")
                                .HasColumnType("integer");

                            b1.Property<int>("Attack")
                                .HasColumnType("integer")
                                .HasColumnName("stat_attack");

                            b1.Property<int>("Defense")
                                .HasColumnType("integer")
                                .HasColumnName("stat_defense");

                            b1.Property<int>("Health")
                                .HasColumnType("integer")
                                .HasColumnName("stat_health");

                            b1.HasKey("MonsterId");

                            b1.ToTable("Monsters");

                            b1.WithOwner()
                                .HasForeignKey("MonsterId");
                        });

                    b.Navigation("Stats")
                        .IsRequired();
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.MonsterLoot", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Game", "Game")
                        .WithMany("MonsterLoots")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Item", "Item")
                        .WithMany("MonsterLoots")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Monster", "Monster")
                        .WithMany("MonsterLoots")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Item");

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.MonsterTagLink", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Monster", "Monster")
                        .WithMany("MonsterTags")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Tag", "Tag")
                        .WithMany("MonsterTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.Quest", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Game", "Game")
                        .WithMany("Quests")
                        .HasForeignKey("GameId");

                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Quest", "ParentQuest")
                        .WithMany("ChildQuests")
                        .HasForeignKey("ParentQuestId");

                    b.Navigation("Game");

                    b.Navigation("ParentQuest");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.QuestEncounter", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Monster", "Monster")
                        .WithMany("QuestEncounters")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Quest", "Quest")
                        .WithMany("QuestEncounters")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.QuestLocationLink", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Location", "Location")
                        .WithMany("QuestLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Quest", "Quest")
                        .WithMany("QuestLocations")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.QuestReward", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Item", "Item")
                        .WithMany("QuestRewards")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Quest", "Quest")
                        .WithMany("QuestRewards")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.QuestTagLink", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Quest", "Quest")
                        .WithMany("QuestTags")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Tag", "Tag")
                        .WithMany("QuestTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.TreasureItem", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Item", "Item")
                        .WithMany("TreasureItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvcinaHra.Shared.Domain.Entities.TreasureQuest", "TreasureQuest")
                        .WithMany("TreasureItems")
                        .HasForeignKey("TreasureQuestId");

                    b.Navigation("Game");

                    b.Navigation("Item");

                    b.Navigation("TreasureQuest");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.TreasureQuest", b =>
                {
                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Game", "Game")
                        .WithMany("TreasureQuests")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvcinaHra.Shared.Domain.Entities.Location", "Location")
                        .WithMany("TreasureQuests")
                        .HasForeignKey("LocationId");

                    b.HasOne("OvcinaHra.Shared.Domain.Entities.SecretStash", "SecretStash")
                        .WithMany("TreasureQuests")
                        .HasForeignKey("SecretStashId");

                    b.Navigation("Game");

                    b.Navigation("Location");

                    b.Navigation("SecretStash");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.BattlefieldBonus", b =>
                {
                    b.Navigation("TimeSlots");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.Building", b =>
                {
                    b.Navigation("CraftingRequirements");

                    b.Navigation("GameBuildings");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.Character", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.CharacterAssignment", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.CraftingRecipe", b =>
                {
                    b.Navigation("BuildingRequirements");

                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.Game", b =>
                {
                    b.Navigation("BattlefieldBonuses");

                    b.Navigation("CraftingRecipes");

                    b.Navigation("GameBuildings");

                    b.Navigation("GameEvents");

                    b.Navigation("GameItems");

                    b.Navigation("GameLocations");

                    b.Navigation("GameMonsters");

                    b.Navigation("GameNpcs");

                    b.Navigation("GameSecretStashes");

                    b.Navigation("MonsterLoots");

                    b.Navigation("Quests");

                    b.Navigation("TimeSlots");

                    b.Navigation("TreasureQuests");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.GameEvent", b =>
                {
                    b.Navigation("EventLocations");

                    b.Navigation("EventNpcs");

                    b.Navigation("EventQuests");

                    b.Navigation("EventTimeSlots");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.GameTimeSlot", b =>
                {
                    b.Navigation("EventTimeSlots");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.Item", b =>
                {
                    b.Navigation("CraftingIngredients");

                    b.Navigation("GameItems");

                    b.Navigation("MonsterLoots");

                    b.Navigation("QuestRewards");

                    b.Navigation("TreasureItems");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.Location", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("EventLocations");

                    b.Navigation("GameLocations");

                    b.Navigation("GameSecretStashes");

                    b.Navigation("QuestLocations");

                    b.Navigation("TreasureQuests");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.Monster", b =>
                {
                    b.Navigation("GameMonsters");

                    b.Navigation("MonsterLoots");

                    b.Navigation("MonsterTags");

                    b.Navigation("QuestEncounters");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.Npc", b =>
                {
                    b.Navigation("EventNpcs");

                    b.Navigation("GameNpcs");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.Quest", b =>
                {
                    b.Navigation("ChildQuests");

                    b.Navigation("EventQuests");

                    b.Navigation("QuestEncounters");

                    b.Navigation("QuestLocations");

                    b.Navigation("QuestRewards");

                    b.Navigation("QuestTags");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.SecretStash", b =>
                {
                    b.Navigation("GameSecretStashes");

                    b.Navigation("TreasureQuests");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.Tag", b =>
                {
                    b.Navigation("MonsterTags");

                    b.Navigation("QuestTags");
                });

            modelBuilder.Entity("OvcinaHra.Shared.Domain.Entities.TreasureQuest", b =>
                {
                    b.Navigation("TreasureItems");
                });
#pragma warning restore 612, 618
        }
    }
}
